<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42059" started-at="2018-05-10T11:28:52Z" finished-at="2018-05-10T11:29:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42059" started-at="2018-05-10T11:28:52Z" finished-at="2018-05-10T11:29:34Z">
      <class name="testcases.TC003_CreateLead">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="beforeSuite" is-config="true" duration-ms="2296" started-at="2018-05-10T11:28:50Z" finished-at="2018-05-10T11:28:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="setData" is-config="true" duration-ms="1" started-at="2018-05-10T11:28:52Z" finished-at="2018-05-10T11:28:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="beforeTest" is-config="true" duration-ms="3" started-at="2018-05-10T11:28:52Z" finished-at="2018-05-10T11:28:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="beforeMethod" is-config="true" duration-ms="21132" started-at="2018-05-10T11:28:55Z" finished-at="2018-05-10T11:29:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginAndLogout(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="loginAndLogout" duration-ms="765" started-at="2018-05-10T11:29:16Z" data-provider="fetchData" finished-at="2018-05-10T11:29:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[DemoSalesManager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[crmsfa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[swapnadeep]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[sss]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[abcaa]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at utils.Reporter.reportStep(Reporter.java:61)
at utils.Reporter.reportStep(Reporter.java:71)
at wdMethods.SeMethods.type(SeMethods.java:121)
at pages.LoginPage.enterUserName(LoginPage.java:21)
at testcases.TC003_CreateLead.loginAndLogout(TC003_CreateLead.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndLogout -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="afterMethod" is-config="true" duration-ms="1370" started-at="2018-05-10T11:29:17Z" finished-at="2018-05-10T11:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="beforeMethod" is-config="true" duration-ms="6498" started-at="2018-05-10T11:29:18Z" finished-at="2018-05-10T11:29:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginAndLogout(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="loginAndLogout" duration-ms="628" started-at="2018-05-10T11:29:24Z" data-provider="fetchData" finished-at="2018-05-10T11:29:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[DemoSalesManager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[crmsfa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[swapnadeep]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[sss]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dd]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at utils.Reporter.reportStep(Reporter.java:61)
at utils.Reporter.reportStep(Reporter.java:71)
at wdMethods.SeMethods.type(SeMethods.java:121)
at pages.LoginPage.enterUserName(LoginPage.java:21)
at testcases.TC003_CreateLead.loginAndLogout(TC003_CreateLead.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndLogout -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="afterMethod" is-config="true" duration-ms="1009" started-at="2018-05-10T11:29:25Z" finished-at="2018-05-10T11:29:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="beforeMethod" is-config="true" duration-ms="6621" started-at="2018-05-10T11:29:26Z" finished-at="2018-05-10T11:29:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginAndLogout(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="loginAndLogout" duration-ms="621" started-at="2018-05-10T11:29:33Z" data-provider="fetchData" finished-at="2018-05-10T11:29:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[DemoSalesManager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[crmsfa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[swapnadeep]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[io]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at utils.Reporter.reportStep(Reporter.java:61)
at utils.Reporter.reportStep(Reporter.java:71)
at wdMethods.SeMethods.type(SeMethods.java:121)
at pages.LoginPage.enterUserName(LoginPage.java:21)
at testcases.TC003_CreateLead.loginAndLogout(TC003_CreateLead.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndLogout -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="afterMethod" is-config="true" duration-ms="1050" started-at="2018-05-10T11:29:33Z" finished-at="2018-05-10T11:29:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="afterTest" is-config="true" duration-ms="1" started-at="2018-05-10T11:29:34Z" finished-at="2018-05-10T11:29:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.TC003_CreateLead@1213b92]" name="afterSuite" is-config="true" duration-ms="1407" started-at="2018-05-10T11:29:35Z" finished-at="2018-05-10T11:29:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC003_CreateLead -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
